---
- name: Define content to file from variables.
  hosts: all
  become: yes
  tasks:
    - name: Create "{{ directory }}" directory.
      ansible.builtin.file:
        path: "{{ directory }}"
        state: directory

    - name: Write content to "{{ file }}" file.
      ansible.builtin.copy:
        dest: "{{ directory }}/{{ file }}"
        content: "{{ content }}"
        
